import { ISbom } from '@/models/ISbom';

export const EXAMPLE_IMAGES = [
  { id: 'nginx:1.21', name: 'nginx:1.21', description: 'Popular web server' },
  { id: 'node:18-alpine', name: 'node:18-alpine', description: 'Node.js runtime' },
  { id: 'postgres:14', name: 'postgres:14', description: 'PostgreSQL database' },
  { id: 'redis:7-alpine', name: 'redis:7-alpine', description: 'Redis cache' },
];

export const MOCK_SBOMS: Record<string, ISbom[]> = {
  'nginx:1.21': [
    {
      format: 'SPDX',
      tool: 'Syft',
      toolInfo: { name: 'Syft', version: '0.100.0', vendor: 'Anchore', format: 'SPDX' },
      imageId: 'nginx:1.21',
      timestamp: '2024-11-01T10:00:00Z',
      packages: [
        {
          name: 'openssl',
          version: '1.1.1',
          supplier: 'OpenSSL',
          license: 'Apache-2.0',
          packageType: 'library',
          hash: 'sha256:a1b2c3d4e5f6',
          purl: 'pkg:deb/debian/openssl@1.1.1?arch=amd64',
          cpe: 'cpe:2.3:a:openssl:openssl:1.1.1:*:*:*:*:*:*:*',
        },
        {
          name: 'zlib',
          version: '1.2.11',
          supplier: 'zlib',
          license: 'Zlib',
          packageType: 'library',
          hash: 'sha256:b2c3d4e5f6a1',
          purl: 'pkg:deb/debian/zlib@1.2.11?arch=amd64',
        },
        {
          name: 'pcre',
          version: '8.44',
          supplier: 'PCRE',
          license: 'BSD-3-Clause',
          packageType: 'library',
          purl: 'pkg:deb/debian/pcre@8.44',
        },
        {
          name: 'nginx',
          version: '1.21.0',
          supplier: 'NGINX',
          license: 'BSD-2-Clause',
          packageType: 'binary',
          hash: 'sha256:c3d4e5f6a1b2',
          purl: 'pkg:deb/debian/nginx@1.21.0?arch=amd64',
        },
        {
          name: 'libc6',
          version: '2.31',
          supplier: 'GNU',
          license: 'LGPL-2.1',
          packageType: 'os',
          purl: 'pkg:deb/debian/libc6@2.31?arch=amd64',
        },
      ],
    },
    {
      format: 'CycloneDX',
      tool: 'Trivy',
      toolInfo: { name: 'Trivy', version: '0.48.0', vendor: 'Aqua Security', format: 'CycloneDX' },
      imageId: 'nginx:1.21',
      timestamp: '2024-11-01T10:05:00Z',
      packages: [
        {
          name: 'openssl',
          version: '1.1.1',
          supplier: 'OpenSSL',
          license: 'Apache-2.0',
          packageType: 'library',
          hash: 'sha256:a1b2c3d4e5f6',
          purl: 'pkg:deb/debian/openssl@1.1.1?arch=amd64',
          cpe: 'cpe:2.3:a:openssl:openssl:1.1.1:*:*:*:*:*:*:*',
        },
        {
          name: 'zlib',
          version: '1.2.11',
          supplier: 'zlib',
          license: 'Zlib',
          packageType: 'library',
          hash: 'sha256:b2c3d4e5f6a1',
          purl: 'pkg:deb/debian/zlib@1.2.11?arch=amd64',
        },
        {
          name: 'nginx',
          version: '1.21.0',
          supplier: 'NGINX',
          license: 'BSD-2-Clause',
          packageType: 'binary',
          hash: 'sha256:c3d4e5f6a1b2',
          purl: 'pkg:deb/debian/nginx@1.21.0?arch=amd64',
        },
        {
          name: 'curl',
          version: '7.74.0',
          supplier: 'curl',
          license: 'MIT',
          packageType: 'binary',
          purl: 'pkg:deb/debian/curl@7.74.0?arch=amd64',
        },
        {
          name: 'libc6',
          version: '2.31',
          supplier: 'GNU',
          license: 'LGPL-2.1',
          packageType: 'os',
          purl: 'pkg:deb/debian/libc6@2.31?arch=amd64',
        },
      ],
    },
    {
      format: 'SPDX',
      tool: 'Docker Scout',
      toolInfo: { name: 'Docker Scout', version: '1.2.0', vendor: 'Docker Inc.', format: 'SPDX' },
      imageId: 'nginx:1.21',
      timestamp: '2024-11-01T10:10:00Z',
      packages: [
        {
          name: 'openssl',
          version: '1.1.1',
          supplier: 'OpenSSL',
          license: 'Apache-2.0',
          packageType: 'library',
          hash: 'sha256:a1b2c3d4e5f6',
          purl: 'pkg:deb/debian/openssl@1.1.1?arch=amd64',
          cpe: 'cpe:2.3:a:openssl:openssl:1.1.1:*:*:*:*:*:*:*',
        },
        {
          name: 'nginx',
          version: '1.21.0',
          supplier: 'NGINX',
          license: 'BSD-2-Clause',
          packageType: 'binary',
          hash: 'sha256:c3d4e5f6a1b2',
          purl: 'pkg:deb/debian/nginx@1.21.0?arch=amd64',
        },
        {
          name: 'libc6',
          version: '2.31',
          supplier: 'GNU',
          license: 'LGPL-2.1',
          packageType: 'os',
          purl: 'pkg:deb/debian/libc6@2.31?arch=amd64',
        },
        {
          name: 'libssl1.1',
          version: '1.1.1n',
          supplier: 'OpenSSL',
          license: 'Apache-2.0',
          packageType: 'library',
          purl: 'pkg:deb/debian/libssl1.1@1.1.1n?arch=amd64',
        },
      ],
    },
  ],
  'node:18-alpine': [
    {
      format: 'SPDX',
      tool: 'Syft',
      toolInfo: { name: 'Syft', version: '0.100.0', vendor: 'Anchore', format: 'SPDX' },
      imageId: 'node:18-alpine',
      timestamp: '2024-11-01T11:00:00Z',
      packages: [
        {
          name: 'nodejs',
          version: '18.12.0',
          supplier: 'Node.js',
          license: 'MIT',
          packageType: 'binary',
          purl: 'pkg:apk/alpine/nodejs@18.12.0?arch=x86_64',
        },
        {
          name: 'npm',
          version: '8.19.2',
          supplier: 'npm',
          license: 'Artistic-2.0',
          packageType: 'npm',
          purl: 'pkg:npm/npm@8.19.2',
        },
        {
          name: 'openssl',
          version: '3.0.7',
          supplier: 'OpenSSL',
          license: 'Apache-2.0',
          packageType: 'library',
          purl: 'pkg:apk/alpine/openssl@3.0.7?arch=x86_64',
        },
        {
          name: 'express',
          version: '4.18.2',
          supplier: 'npm',
          license: 'MIT',
          packageType: 'npm',
          purl: 'pkg:npm/express@4.18.2',
        },
      ],
    },
    {
      format: 'CycloneDX',
      tool: 'Trivy',
      toolInfo: { name: 'Trivy', version: '0.48.0', vendor: 'Aqua Security', format: 'CycloneDX' },
      imageId: 'node:18-alpine',
      timestamp: '2024-11-01T11:05:00Z',
      packages: [
        {
          name: 'nodejs',
          version: '18.12.0',
          supplier: 'Node.js',
          license: 'MIT',
          packageType: 'binary',
          purl: 'pkg:apk/alpine/nodejs@18.12.0?arch=x86_64',
        },
        {
          name: 'npm',
          version: '8.19.2',
          supplier: 'npm',
          license: 'Artistic-2.0',
          packageType: 'npm',
          purl: 'pkg:npm/npm@8.19.2',
        },
        {
          name: 'zlib',
          version: '1.2.13',
          supplier: 'zlib',
          license: 'Zlib',
          packageType: 'library',
          purl: 'pkg:apk/alpine/zlib@1.2.13?arch=x86_64',
        },
        {
          name: 'musl',
          version: '1.2.3',
          supplier: 'musl',
          license: 'MIT',
          packageType: 'os',
          purl: 'pkg:apk/alpine/musl@1.2.3?arch=x86_64',
        },
      ],
    },
    {
      format: 'SPDX',
      tool: 'Docker Scout',
      toolInfo: { name: 'Docker Scout', version: '1.2.0', vendor: 'Docker Inc.', format: 'SPDX' },
      imageId: 'node:18-alpine',
      timestamp: '2024-11-01T11:10:00Z',
      packages: [
        {
          name: 'nodejs',
          version: '18.12.0',
          supplier: 'Node.js',
          license: 'MIT',
          packageType: 'binary',
          purl: 'pkg:apk/alpine/nodejs@18.12.0?arch=x86_64',
        },
        {
          name: 'openssl',
          version: '3.0.7',
          supplier: 'OpenSSL',
          license: 'Apache-2.0',
          packageType: 'library',
          purl: 'pkg:apk/alpine/openssl@3.0.7?arch=x86_64',
        },
        {
          name: 'musl',
          version: '1.2.3',
          supplier: 'musl',
          license: 'MIT',
          packageType: 'os',
          purl: 'pkg:apk/alpine/musl@1.2.3?arch=x86_64',
        },
      ],
    },
  ],
};
