apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: ClusterIP
