name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract tag
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        
      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/sbomvert/sbomvert:${{ steps.tag.outputs.TAG }} \
            -t ghcr.io/sbomvert/sbomvert:latest \
            --push \
            .

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Package and push Helm chart
        run: |
          sed -i "s/appVersion: .*/appVersion: \"${{ steps.tag.outputs.TAG }}\"/" charts/sbomvert/Chart.yaml
          helm package charts/sbomvert --version ${{ steps.tag.outputs.TAG }} --app-version ${{ steps.tag.outputs.TAG }}
          helm push sbomvert-${{ steps.tag.outputs.TAG }}.tgz oci://ghcr.io/sbomvert/charts