name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Extract tag
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
        
      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/sbomvert/sbomvert:${{ steps.tag.outputs.TAG }} \
            -t ghcr.io/sbomvert/sbomvert:latest \
            --push \
            .

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Package and push Helm chart
        run: |
          sed -i "s/appVersion: .*/appVersion: \"${{ steps.tag.outputs.TAG }}\"/" charts/sbomvert/Chart.yaml
          helm package charts/sbomvert --version ${{ steps.tag.outputs.TAG }} --app-version ${{ steps.tag.outputs.TAG }}
          helm push sbomvert-${{ steps.tag.outputs.TAG }}.tgz oci://ghcr.io/sbomvert/charts